# GitHub Sponsors and other funding methods
# Learn more: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: joelc0193  # Replace with your GitHub username if you have GitHub Sponsors enabled

# Other options (uncomment and fill in as needed):
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with your Open Collective name
# ko_fi: # Replace with your Ko-fi username
# liberapay: # Replace with a single Liberapay username
# custom:
#   - "https://www.buymeacoffee.com/yourusername"
#   - "https://paypal.me/yourusername"
