import http from "k6/http";
import { check } from "k6";
import { REST_URL, FUNCTIONS_URL, SUPABASE_ANON_KEY } from "../config/env.js";

// Expected statuses — tell k6 these aren't errors for http_req_failed metric
const EDGE_FN_EXPECTED = { responseCallback: http.expectedStatuses(200, 400) };
const JOIN_EXPECTED = { responseCallback: http.expectedStatuses(201, 409) };

/**
 * PostgREST request helper.
 */
export function restRequest(method, path, token, body, tagName) {
  const headers = {
    "Content-Type": "application/json",
    apikey: SUPABASE_ANON_KEY,
    Authorization: `Bearer ${token}`,
  };

  // For inserts, request the inserted row back
  if (method === "POST" && !path.includes("/rpc/")) {
    headers["Prefer"] = "return=representation";
  }

  const url = `${REST_URL}${path}`;
  const opts = { headers, tags: { name: tagName || path } };

  if (method === "GET") return http.get(url, opts);
  if (method === "POST") return http.post(url, JSON.stringify(body), opts);
  if (method === "PATCH") return http.patch(url, JSON.stringify(body), opts);
  if (method === "DELETE") return http.del(url, null, opts);
  return http.request(method, url, JSON.stringify(body), opts);
}

/**
 * Call an edge function.
 */
export function callFunction(name, token, body, tagName) {
  const res = http.post(
    `${FUNCTIONS_URL}/${name}`,
    JSON.stringify(body),
    {
      headers: {
        "Content-Type": "application/json",
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${token}`,
      },
      tags: { name: tagName || name },
      ...EDGE_FN_EXPECTED,
    }
  );
  return res;
}

/**
 * Call get_my_chats_dashboard RPC.
 * Requires p_user_id parameter.
 */
export function getDashboard(token, userId) {
  const res = restRequest("POST", "/rpc/get_my_chats_dashboard", token, {
    p_user_id: userId,
    p_language_code: "en",
  }, "dashboard");

  check(res, {
    "dashboard: status 200": (r) => r.status === 200,
  });

  return res;
}

/**
 * Create a public chat with k6 test prefix.
 */
export function createChat(token, chatName) {
  const res = restRequest("POST", "/chats", token, {
    name: chatName,
    initial_message: "Load test chat - auto generated by k6",
    access_method: "public",
    is_active: true,
  }, "create_chat");

  const ok = check(res, {
    "create_chat: status 201": (r) => r.status === 201,
    "create_chat: has id": (r) => {
      try { return !!JSON.parse(r.body)[0]?.id; }
      catch { return false; }
    },
  });

  if (!ok) return null;

  try {
    const data = JSON.parse(res.body);
    return data[0];
  } catch {
    return null;
  }
}

/**
 * List public k6 test chats that can be joined.
 */
export function listTestChats(token) {
  const res = restRequest(
    "GET",
    `/chats?name=like.k6_loadtest_*&access_method=eq.public&is_active=eq.true&select=id,name&limit=50`,
    token,
    null,
    "list_test_chats"
  );

  if (res.status !== 200) return [];

  try {
    return JSON.parse(res.body) || [];
  } catch {
    return [];
  }
}

/**
 * Join a chat as a participant.
 * Includes user_id for RLS policy (requires user_id = auth.uid()).
 */
export function joinChat(token, chatId, displayName, userId) {
  const res = http.post(
    `${REST_URL}/participants`,
    JSON.stringify({
      chat_id: chatId,
      display_name: displayName,
      user_id: userId,
      status: "active",
    }),
    {
      headers: {
        "Content-Type": "application/json",
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${token}`,
        Prefer: "return=representation",
      },
      tags: { name: "join_chat" },
      ...JOIN_EXPECTED,
    }
  );

  check(res, {
    "join_chat: status 201 or 409": (r) => r.status === 201 || r.status === 409,
  });

  return res;
}

/**
 * Join a chat via SECURITY DEFINER RPC — bypasses per-row RLS.
 * Combines join + get_participant into one call. Idempotent.
 * Returns { id, display_name, status, is_host } or null.
 */
export function joinChatRpc(token, chatId, displayName) {
  const res = restRequest(
    "POST",
    "/rpc/join_chat_returning_participant",
    token,
    { p_chat_id: chatId, p_display_name: displayName },
    "join_chat"
  );

  const ok = check(res, {
    "join_chat: status 200": (r) => r.status === 200,
  });

  if (!ok) return null;

  try {
    const data = JSON.parse(res.body);
    return data && data.length > 0 ? data[0] : null;
  } catch {
    return null;
  }
}

/**
 * Submit a proposition via edge function.
 * The edge function expects { round_id, participant_id, content }.
 */
export function submitProposition(token, roundId, participantId, content) {
  const res = http.post(
    `${FUNCTIONS_URL}/submit-proposition`,
    JSON.stringify({ round_id: roundId, participant_id: participantId, content }),
    {
      headers: {
        "Content-Type": "application/json",
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${token}`,
      },
      tags: { name: "submit_proposition" },
      ...EDGE_FN_EXPECTED,
    }
  );

  check(res, {
    "submit_prop: status 200 or 400": (r) => r.status === 200 || r.status === 400,
  });

  return res;
}

/**
 * Submit ratings via edge function.
 */
export function submitRatings(token, chatId, ratings) {
  const res = http.post(
    `${FUNCTIONS_URL}/submit-ratings`,
    JSON.stringify({ chat_id: chatId, ratings }),
    {
      headers: {
        "Content-Type": "application/json",
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${token}`,
      },
      tags: { name: "submit_ratings" },
      ...EDGE_FN_EXPECTED,
    }
  );

  check(res, {
    "submit_ratings: status 200 or 400": (r) => r.status === 200 || r.status === 400,
  });

  return res;
}

/**
 * Upsert a single grid_ranking via SECURITY DEFINER RPC.
 * Bypasses per-row RLS evaluation which causes statement_timeout
 * under concurrent load (same issue as get_propositions_for_rating).
 */
export function upsertSingleRating(token, roundId, participantId, propositionId, gridPosition) {
  const res = restRequest(
    "POST",
    "/rpc/upsert_grid_ranking",
    token,
    {
      p_round_id: roundId,
      p_participant_id: participantId,
      p_proposition_id: propositionId,
      p_grid_position: gridPosition,
    },
    "upsert_grid_ranking"
  );

  check(res, {
    "upsert_grid_ranking: status 204": (r) => r.status === 204,
  });

  return res;
}

/**
 * Create the mega-chat for the 5,000-user load test.
 * Auto mode with short timers and low thresholds.
 * Returns the chat object or null.
 */
export function createMegaChat(token) {
  const res = restRequest("POST", "/chats", token, {
    name: "k6_loadtest_mega_5000",
    initial_message: "5000-user load test — realistic propose/rate flow",
    access_method: "public",
    start_mode: "auto",
    auto_start_participant_count: 50,
    proposing_duration_seconds: 120,
    rating_duration_seconds: 120,
    rating_start_mode: "auto",
    proposing_minimum: 3,
    rating_minimum: 2,
    proposing_threshold_percent: 1,
    proposing_threshold_count: 50,
    rating_threshold_percent: 1,
    rating_threshold_count: 50,
    confirmation_rounds_required: 2,
    propositions_per_user: 1,
    enable_ai_participant: false,
    translations_enabled: false,
    is_active: true,
  }, "create_mega_chat");

  const ok = check(res, {
    "create_mega_chat: status 201": (r) => r.status === 201,
    "create_mega_chat: has id": (r) => {
      try { return !!JSON.parse(r.body)[0]?.id; }
      catch { return false; }
    },
  });

  if (!ok) return null;

  try {
    const data = JSON.parse(res.body);
    return data[0];
  } catch {
    return null;
  }
}

/**
 * Find the existing mega-chat by name.
 * Returns { id } or null.
 */
export function findMegaChat(token) {
  const res = restRequest(
    "GET",
    `/chats?name=eq.k6_loadtest_mega_5000&is_active=eq.true&select=id&limit=1`,
    token,
    null,
    "find_mega_chat"
  );

  if (res.status !== 200) return null;

  try {
    const data = JSON.parse(res.body);
    return data && data.length > 0 ? data[0] : null;
  } catch {
    return null;
  }
}
